# Generated by Django 5.2 on 2025-04-14 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='npme',
            new_name='nome',
        ),
    ]
